### PR TITLE
Finished Star Course

### PR DESCRIPTION
**Pull request by sillyo39**
All of star course has been completed with the png files for the completed preview. You can thank andre111 for the png files. I grabbed them from his dump of the game.

EDIT: Not done yet.

### CODE REVIEW

**Comment by sillyo39** [comment]
Will do. Give me a few to fix them.

**Comment by sillyo39** [comment]
All done.

**Comment by Substance12** [comment]
Thanks a ton for the help. I'll probably merge it tomorrow, I gotta do something now.

**Comment by sillyo39** [comment]
That is fine. I have to go do some others things now as well.

**Pull request merged**
